#ifndef __HIBUS_BUSYBOX_H__
#define __HIBUS_BUSYBOX_H__

// define error
#define	ERROR_BUSYBOX_OK				0
#define	ERROR_BUSYBOX_INVALID_PARAM		-1
#define	ERROR_BUSYBOX_INSUFFICIENT_MEM	-2
#define	ERROR_BUSYBOX_CONNECT_HIBUS		-3
#define	ERROR_BUSYBOX_WRONG_PROCEDURE	-4
#define	ERROR_BUSYBOX_WRONG_JSON		-5
#define	ERROR_BUSYBOX_FILE_EXIST		-6
#define	ERROR_BUSYBOX_DIR_OPEN			-7
#define	ERROR_BUSYBOX_WORKING_DICT		-8
#define	ERROR_BUSYBOX_NOT_FILE			-9
#define	ERROR_BUSYBOX_NOT_DIRECTORY		-10
#define	ERROR_BUSYBOX_EACCES			-11
#define	ERROR_BUSYBOX_EBUSY				-12
#define	ERROR_BUSYBOX_EFAULT			-13
#define	ERROR_BUSYBOX_EIO				-14
#define	ERROR_BUSYBOX_EISDIR			-15
#define	ERROR_BUSYBOX_ELOOP				-16
#define	ERROR_BUSYBOX_ENAMETOOLONG		-17
#define	ERROR_BUSYBOX_ENOENT			-18
#define	ERROR_BUSYBOX_ENOMEM			-19
#define	ERROR_BUSYBOX_ENOTDIR			-20
#define	ERROR_BUSYBOX_EPERM				-21
#define	ERROR_BUSYBOX_EROFS				-22
#define	ERROR_BUSYBOX_EBADF				-23
#define	ERROR_BUSYBOX_EINVAL			-24
#define	ERROR_BUSYBOX_ESRCH				-25
#define	ERROR_BUSYBOX_UNKONOWN			-26
#define	ERROR_BUSYBOX_CREATE_FILE		-27

#define	ERROR_LOAD_LIB					-100
#define	ERROR_FIND_SYM					-101
#define	ERROR_EXEC_LIB_FUNC				-102

// for file system remote invocation
#define METHOD_HIBUS_BUSYBOX_LS		"ls"
#define METHOD_HIBUS_BUSYBOX_RM		"rm"
#define METHOD_HIBUS_BUSYBOX_RMDIR	"rmdir"
#define METHOD_HIBUS_BUSYBOX_MKDIR	"mkdir"
#define METHOD_HIBUS_BUSYBOX_UNLINK	"unlink"
#define METHOD_HIBUS_BUSYBOX_TOUCH	"touch"
#define	METHOD_HIBUS_BUSYBOX_CHDIR	"chdir"


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

#endif  // __HIBUS_BUSYBOX_H__
